### ISSUE TITLE
Rebuild images (based on alpine)

### ISSUE THREAD

**Issue by nvtkaszpir** [Gradiant/dockerized-hadoop#1]
Current docker images are based on java jre apline - which contains jre 1.8u171 ... dates around 2018.07.17

It requires to pass additional  java opts to processes via env var like JAVA_OPTS such as:
``` 
-XX:+UnlockExperimentalVMOptions \
-XX:+UseCGroupMemoryLimitForHeap \
-XX:MaxRAMFraction=2
```

Fix:
Update base image to java jre alpine (highest is with 1.8u212 https://hub.docker.com/_/openjdk?tab=tags&page=1&name=8u212-jre-alpine ) which has backported fixes for detecting containerized apps ( see https://www.oracle.com/technetwork/java/javase/8u191-relnotes-5032181.html)
and looks like it just needs bumping in corresponding Dockerfiles here and related projects using this images.

This will help in running the stack in docker/k8s without the need of passing fine grained paramters to adjust java options to avoid OOM kills.

```bash
docker pull openjdk:8-jre-alpine
8-jre-alpine: Pulling from library/openjdk
e7c96db7181b: Pull complete 
f910a506b6cb: Pull complete 
b6abafe80f63: Pull complete 
Digest: sha256:f362b165b870ef129cbe730f29065ff37399c0aa8bcab3e44b51c302938c9193
Status: Downloaded newer image for openjdk:8-jre-alpine
docker.io/library/openjdk:8-jre-alpine


docker run -it openjdk:8-jre-alpine /usr/bin/java -version
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (IcedTea 3.12.0) (Alpine 8.212.04-r0)
OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)
```

**Comment by cgiraldo** [comment]
Done.
We also move alpine images to the `alpine` branch. 
Current master branch is debian based to reduce build time (we don't have to build from sources).
