### ISSUE TITLE
multiarch support

### ISSUE THREAD

**Issue by nvtkaszpir** [Gradiant/dockerized-hadoop#5]
Looks nice but I suggest remove unsupported architectures, unless you really have access to those:
- arm32v7
- arm64v8
- i386
- ppc64le
- s390x

I suggest sticking to the:
- amd64
- (maybe)  arm32v7 (but those usually got not enough memory on the device)
- (maybe) arm64v8.

Otherwise it will be just maintenance burden that no one uses - aka dead code.

**Comment by cgiraldo** [comment]
Multiarch support is provided from generic templates at Gradiant.
 
Even if you are right and we cannot give support for all the architectures, we will keep them and let the community discover them and maybe test and fix them.
